FROM python:3.8.2-slim-buster 
ARG VERSION=0.0.4
WORKDIR /workspace/picospace
ENV VERSION=${VERSION}


RUN apt-get update
RUN apt-get install -y git
RUN git clone https://github.com/alicata/build-debug.git



CMD ["python", "build-debug/projects/image/main.py", "`${VERSION}`"]
