FROM python:3.8.2-slim-buster 

ARG VERSION=0.0.1

WORKDIR /workspace/picospace

ENV VERSION=${VERSION}

COPY projects/image projects/image

RUN ls > test.log 

CMD ["python", "projects/image/main.py", "`${VERSION}`"]
