FROM python:3.8.2-slim-buster 

ARG VERSION=0.0.1

WORKDIR /workspace/picospace

ENV VERSION=${VERSION}

https://github.com/alicata/build-debug.git


CMD ["python", "build-debug/projects/image/main.py", "`${VERSION}`"]
